---
title: "Kernel Checks"
author: "Alex Lehner and Alex Gordon"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(Rcpp)
library(RcppArmadillo)
library(tidyverse)
library(gridExtra)
library(here)

knitr::opts_chunk$set(echo = TRUE)
```

## Setup

```{r}
setwd(here())
sourceCpp("distmat.cpp")
```

## Create Grid

```{r}
grid_size <- 100
cutoff <- 100
center <- c(0, 0)

lat_vals <- seq(-1, 1, length.out = grid_size)
lon_vals <- seq(-1, 1, length.out = grid_size)
grid <- expand.grid(lon_vals, lat_vals)
colnames(grid) <- c("lon", "lat")
M <- as.matrix(grid)
```

## Run Kernels

```{r}
kernels <- c("Bartlett", "Epanechnikov", "Gaussian", "Parzen", "Biweight", "Uniform")
results <- list()

center_index <- which.min((grid$lat - 0)^2 + (grid$lon - 0)^2)

for (k in kernels) {
  dmat <- DistMat(M, cutoff, k)
  results[[k]] <- data.frame(lat = grid[,1], lon = grid[,2], weight = dmat[, center_index])
}
```

## Print Graphs

```{r}
plot_kernel <- function(data, kernel_name) {
  ggplot(data, aes(x = lon, y = lat, fill = weight)) +
    geom_tile() +
    scale_fill_gradient(low = "white", high = "green") +
    theme_minimal() +
    labs(title = paste(kernel_name, "Kernel"), fill = "Weight")
}

invisible(lapply(names(results), function(k) print(plot_kernel(results[[k]], k))))
```