# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create Distance Matrix
#'
#' @export
#'
#' @param M a matrix of locations (n x 2, latitude and longitude)
#' @param cutoff the distance cutoff (bandwidth) in km
#' @param kernel (string) kernel function (default is bartlett-triangular)
#' @param dist_fn (string) distance function (Haversine)
#'
#' @return A symmetric n x n matrix of kernel weights with 1s on the diagonal.
DistMat <- function(M, cutoff, kernel = "bartlett", dist_fn = "Haversine") {
    .Call(`_SpatialInference_DistMat`, M, cutoff, kernel, dist_fn)
}

#' Spatial Variance Component (X'ee'X)
#'
#' @export
#'
#' @param M matrix of locations (n x 2, latitude and longitude)
#' @param cutoff the distance cutoff (bandwidth) in km
#' @param X model matrix (n x k)
#' @param e vector of residuals (length n)
#' @param n1 number of observations
#' @param k number of regressors
#' @param kernel (string) kernel function (default is bartlett-triangular)
#' @param dist_fn (string) distance function (Haversine)
#'
#' @return A k x k matrix representing the spatial X'ee'X component.
XeeXhC <- function(M, cutoff, X, e, n1, k, kernel = "bartlett", dist_fn = "Haversine") {
    .Call(`_SpatialInference_XeeXhC`, M, cutoff, X, e, n1, k, kernel, dist_fn)
}

#' Spatial Variance Component for Balanced Panel
#'
#' @export
#'
#' @param dmat pre-computed distance matrix (n x n)
#' @param X model matrix (n x k)
#' @param e vector of residuals (length n)
#' @param n1 number of observations
#' @param k number of regressors
#'
#' @return A k x k matrix representing the spatial X'ee'X component.
Bal_XeeXhC <- function(dmat, X, e, n1, k) {
    .Call(`_SpatialInference_Bal_XeeXhC`, dmat, X, e, n1, k)
}

#' Spatial Variance Component for Large Datasets
#'
#' Memory-efficient variant that avoids constructing the full n x n distance matrix.
#'
#' @export
#'
#' @param M matrix of locations (n x 2, latitude and longitude)
#' @param cutoff the distance cutoff (bandwidth) in km
#' @param X model matrix (n x k)
#' @param e vector of residuals (length n)
#' @param n1 number of observations
#' @param k number of regressors
#' @param kernel (string) kernel function (default is bartlett-triangular)
#' @param dist_fn (string) distance function (Haversine)
#'
#' @return A k x k matrix representing the spatial X'ee'X component.
XeeXhC_Lg <- function(M, cutoff, X, e, n1, k, kernel = "bartlett", dist_fn = "Haversine") {
    .Call(`_SpatialInference_XeeXhC_Lg`, M, cutoff, X, e, n1, k, kernel, dist_fn)
}

#' Temporal Variance Component (Time Dimension)
#'
#' @export
#'
#' @param times numeric vector of time period identifiers
#' @param cutoff the lag cutoff (number of time periods)
#' @param X model matrix (n x k)
#' @param e vector of residuals (length n)
#' @param n1 number of observations
#' @param k number of regressors
#'
#' @return A k x k matrix representing the temporal X'ee'X component.
TimeDist <- function(times, cutoff, X, e, n1, k) {
    .Call(`_SpatialInference_TimeDist`, times, cutoff, X, e, n1, k)
}

